/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppStartRouteImport } from './routes/_app/start'
import { Route as AppCConversationIdRouteImport } from './routes/_app/c/$conversationId'
import { Route as AppPUsernameRouteImport } from './routes/_app/p/$username'
import { Route as AuthSignInSplatRouteImport } from './routes/_auth/sign-in.$'
import { Route as AuthSignUpSplatRouteImport } from './routes/_auth/sign-up.$'
import { Route as ApiPusherAuthRouteImport } from './routes/api/pusher/auth'
import { Route as ApiTrpcSplatRouteImport } from './routes/api/trpc/$'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppStartRoute = AppStartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => AppRoute,
} as any)
const AppCConversationIdRoute = AppCConversationIdRouteImport.update({
  id: '/c/$conversationId',
  path: '/c/$conversationId',
  getParentRoute: () => AppRoute,
} as any)
const AppPUsernameRoute = AppPUsernameRouteImport.update({
  id: '/p/$username',
  path: '/p/$username',
  getParentRoute: () => AppRoute,
} as any)
const AuthSignInSplatRoute = AuthSignInSplatRouteImport.update({
  id: '/_auth/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthSignUpSplatRoute = AuthSignUpSplatRouteImport.update({
  id: '/_auth/sign-up/$',
  path: '/sign-up/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPusherAuthRoute = ApiPusherAuthRouteImport.update({
  id: '/api/pusher/auth',
  path: '/api/pusher/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTrpcSplatRoute = ApiTrpcSplatRouteImport.update({
  id: '/api/trpc/$',
  path: '/api/trpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/start': typeof AppStartRoute
  '/c/$conversationId': typeof AppCConversationIdRoute
  '/p/$username': typeof AppPUsernameRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/api/pusher/auth': typeof ApiPusherAuthRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesByTo {
  '/start': typeof AppStartRoute
  '/': typeof AppIndexRoute
  '/c/$conversationId': typeof AppCConversationIdRoute
  '/p/$username': typeof AppPUsernameRoute
  '/sign-in/$': typeof AuthSignInSplatRoute
  '/sign-up/$': typeof AuthSignUpSplatRoute
  '/api/pusher/auth': typeof ApiPusherAuthRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/start': typeof AppStartRoute
  '/_app/': typeof AppIndexRoute
  '/_app/c/$conversationId': typeof AppCConversationIdRoute
  '/_app/p/$username': typeof AppPUsernameRoute
  '/_auth/sign-in/$': typeof AuthSignInSplatRoute
  '/_auth/sign-up/$': typeof AuthSignUpSplatRoute
  '/api/pusher/auth': typeof ApiPusherAuthRoute
  '/api/trpc/$': typeof ApiTrpcSplatRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/start'
    | '/c/$conversationId'
    | '/p/$username'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/pusher/auth'
    | '/api/trpc/$'
    | '/api/webhooks/clerk'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/start'
    | '/'
    | '/c/$conversationId'
    | '/p/$username'
    | '/sign-in/$'
    | '/sign-up/$'
    | '/api/pusher/auth'
    | '/api/trpc/$'
    | '/api/webhooks/clerk'
  id:
    | '__root__'
    | '/_app'
    | '/_app/start'
    | '/_app/'
    | '/_app/c/$conversationId'
    | '/_app/p/$username'
    | '/_auth/sign-in/$'
    | '/_auth/sign-up/$'
    | '/api/pusher/auth'
    | '/api/trpc/$'
    | '/api/webhooks/clerk'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  AuthSignInSplatRoute: typeof AuthSignInSplatRoute
  AuthSignUpSplatRoute: typeof AuthSignUpSplatRoute
  ApiPusherAuthRoute: typeof ApiPusherAuthRoute
  ApiTrpcSplatRoute: typeof ApiTrpcSplatRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/start': {
      id: '/_app/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof AppStartRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/c/$conversationId': {
      id: '/_app/c/$conversationId'
      path: '/c/$conversationId'
      fullPath: '/c/$conversationId'
      preLoaderRoute: typeof AppCConversationIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/p/$username': {
      id: '/_app/p/$username'
      path: '/p/$username'
      fullPath: '/p/$username'
      preLoaderRoute: typeof AppPUsernameRouteImport
      parentRoute: typeof AppRoute
    }
    '/_auth/sign-in/$': {
      id: '/_auth/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof AuthSignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/sign-up/$': {
      id: '/_auth/sign-up/$'
      path: '/sign-up/$'
      fullPath: '/sign-up/$'
      preLoaderRoute: typeof AuthSignUpSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/pusher/auth': {
      id: '/api/pusher/auth'
      path: '/api/pusher/auth'
      fullPath: '/api/pusher/auth'
      preLoaderRoute: typeof ApiPusherAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/trpc/$': {
      id: '/api/trpc/$'
      path: '/api/trpc/$'
      fullPath: '/api/trpc/$'
      preLoaderRoute: typeof ApiTrpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppStartRoute: typeof AppStartRoute
  AppIndexRoute: typeof AppIndexRoute
  AppCConversationIdRoute: typeof AppCConversationIdRoute
  AppPUsernameRoute: typeof AppPUsernameRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppStartRoute: AppStartRoute,
  AppIndexRoute: AppIndexRoute,
  AppCConversationIdRoute: AppCConversationIdRoute,
  AppPUsernameRoute: AppPUsernameRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  AuthSignInSplatRoute: AuthSignInSplatRoute,
  AuthSignUpSplatRoute: AuthSignUpSplatRoute,
  ApiPusherAuthRoute: ApiPusherAuthRoute,
  ApiTrpcSplatRoute: ApiTrpcSplatRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
